import fs from 'node:fs/promises';
const memory=JSON.parse(await fs.readFile('state/memory.json','utf8'));
const brand=JSON.parse(await fs.readFile('config/brand.json','utf8'));
const now=Date.now();
const published=memory.items.filter(x=>x.instagram_published_at).sort((a,b)=>Date.parse(b.instagram_published_at)-Date.parse(a.instagram_published_at));
const last=published[0]?Date.parse(published[0].instagram_published_at):0;
const ready=memory.items.filter(x=>x.status==='ready').length;
const publishing=memory.items.filter(x=>x.status==='publishing').length;
const needsReview=memory.items.filter(x=>x.status==='needs_review').length;
const recentErrors=memory.items.filter(x=>x.instagram_error||x.threads_error).slice(-10).map(x=>({key:x.key,instagram:x.instagram_error_class,threads:x.threads_error_class}));
const hoursSinceLast=last?(now-last)/3600000:null;
const healthy=!brand.enabled||publishing>0||ready>0||hoursSinceLast===null||hoursSinceLast<=1;
const report={at:new Date().toISOString(),healthy,ready,publishing,needsReview,lastInstagramPost:published[0]?.instagram_published_at||null,hoursSinceLast,sourceAccounts:JSON.parse(await fs.readFile('config/sources.json','utf8')).instagram_source_accounts.map(x=>x.handle),recentErrors};
await fs.writeFile('health-report.json',JSON.stringify(report,null,2)+'\n');
const summary=process.env.GITHUB_STEP_SUMMARY;
if(summary)await fs.appendFile(summary,`### Very Good Films health\n\n- Status: **${healthy?'healthy':'attention required'}**\n- Ready queue: **${ready}**\n- Publishing: **${publishing}**\n- Needs review: **${needsReview}**\n- Last Instagram post: **${report.lastInstagramPost||'none'}**\n- Hours since last post: **${hoursSinceLast===null?'n/a':hoursSinceLast.toFixed(2)}**\n`);
console.log(JSON.stringify(report));
if(!healthy)process.exitCode=1;
